services:
  postgres:
    image: postgres:17-alpine
    container_name: audio_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: audio_db
    ports:
      - "5432:5432"

  zookeeper:
    image: bitnami/zookeeper
    ports: ["2181:2181"]
  kafka:
    image: bitnami/kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true


  # gateway:
  #   build: .
  #   environment:
  #     LOKI_URL: http://loki:3100
  #   depends_on:
  #     - loki

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ./promtail-config.yaml:/etc/promtail/config.yml
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml