services:
  postgres:
    image: postgres:17-alpine
    container_name: audio_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: audio_db
    ports:
      - "5432:5432"
